from django.urls import path

from . import views


urlpatterns = [
    path("", views.portal_dashboard, name="portal_dashboard"),
    path("sin-acceso/", views.portal_sin_acceso, name="portal_sin_acceso"),
    path("perfil/", views.portal_perfil, name="portal_perfil"),
    path("asistencias/", views.portal_asistencias, name="portal_asistencias"),
    path("permisos/solicitar/", views.portal_permiso_solicitar, name="portal_permiso_solicitar"),
    path("vacaciones/solicitar/", views.portal_vacacion_solicitar, name="portal_vacacion_solicitar"),
    path("marcaciones/solicitar/", views.portal_marcacion_solicitar, name="portal_marcacion_solicitar"),
    path("deudas/", views.portal_deudas, name="portal_deudas"),
    path("documentos/", views.portal_documentos, name="portal_documentos"),
    path("documentos/solicitar/", views.portal_documento_solicitar, name="portal_documento_solicitar"),
    path("documentos/<int:pk>/confirmar/", views.portal_documento_confirmar, name="portal_documento_confirmar"),
    path("notificaciones/", views.portal_notificaciones, name="portal_notificaciones"),
    path("sugerencias/", views.portal_sugerencias, name="portal_sugerencias"),
    path("sugerencias/nueva/", views.portal_sugerencia_crear, name="portal_sugerencia_crear"),
    path("comunicaciones/", views.portal_comunicaciones, name="portal_comunicaciones"),
    path("comunicaciones/<int:pk>/", views.portal_comunicacion_detalle, name="portal_comunicacion_detalle"),
    path("comunicaciones/<int:pk>/confirmar/", views.portal_comunicacion_confirmar, name="portal_comunicacion_confirmar"),
    path("comunicaciones/<int:pk>/descargo/", views.portal_descargo_enviar, name="portal_descargo_enviar"),
    path("bandeja/", views.portal_bandeja, name="portal_bandeja"),
    path("bandeja/permisos/<int:pk>/", views.portal_permiso_gestionar, name="portal_permiso_gestionar"),
    path("bandeja/vacaciones/<int:pk>/", views.portal_vacacion_gestionar, name="portal_vacacion_gestionar"),
    path("bandeja/documentos/<int:pk>/", views.portal_solicitud_documento_gestionar, name="portal_solicitud_documento_gestionar"),
    path("bandeja/marcaciones/<int:pk>/", views.portal_solicitud_marcacion_gestionar, name="portal_solicitud_marcacion_gestionar"),
    path("bandeja/sugerencias/<int:pk>/", views.portal_sugerencia_gestionar, name="portal_sugerencia_gestionar"),
    path("admin/funcionario/<int:funcionario_id>/", views.portal_dashboard, name="portal_admin_funcionario"),
    path("admin/funcionario/<int:funcionario_id>/perfil/", views.portal_perfil, name="portal_admin_perfil"),
    path("admin/funcionario/<int:funcionario_id>/asistencias/", views.portal_asistencias, name="portal_admin_asistencias"),
    path("admin/funcionario/<int:funcionario_id>/permisos/solicitar/", views.portal_permiso_solicitar, name="portal_admin_permiso_solicitar"),
    path("admin/funcionario/<int:funcionario_id>/vacaciones/solicitar/", views.portal_vacacion_solicitar, name="portal_admin_vacacion_solicitar"),
    path("admin/funcionario/<int:funcionario_id>/marcaciones/solicitar/", views.portal_marcacion_solicitar, name="portal_admin_marcacion_solicitar"),
    path("admin/funcionario/<int:funcionario_id>/deudas/", views.portal_deudas, name="portal_admin_deudas"),
    path("admin/funcionario/<int:funcionario_id>/documentos/", views.portal_documentos, name="portal_admin_documentos"),
    path("admin/funcionario/<int:funcionario_id>/documentos/solicitar/", views.portal_documento_solicitar, name="portal_admin_documento_solicitar"),
    path("admin/funcionario/<int:funcionario_id>/documentos/<int:pk>/confirmar/", views.portal_documento_confirmar, name="portal_admin_documento_confirmar"),
    path("admin/funcionario/<int:funcionario_id>/notificaciones/", views.portal_notificaciones, name="portal_admin_notificaciones"),
    path("admin/funcionario/<int:funcionario_id>/sugerencias/", views.portal_sugerencias, name="portal_admin_sugerencias"),
    path("admin/funcionario/<int:funcionario_id>/sugerencias/nueva/", views.portal_sugerencia_crear, name="portal_admin_sugerencia_crear"),
    path("admin/funcionario/<int:funcionario_id>/comunicaciones/", views.portal_comunicaciones, name="portal_admin_comunicaciones"),
    path("admin/funcionario/<int:funcionario_id>/comunicaciones/<int:pk>/", views.portal_comunicacion_detalle, name="portal_admin_comunicacion_detalle"),
    path("admin/funcionario/<int:funcionario_id>/comunicaciones/<int:pk>/confirmar/", views.portal_comunicacion_confirmar, name="portal_admin_comunicacion_confirmar"),
    path("admin/funcionario/<int:funcionario_id>/comunicaciones/<int:pk>/descargo/", views.portal_descargo_enviar, name="portal_admin_descargo_enviar"),
]
