# Generated by Django 5.2 on 2026-04-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=30, unique=True)),
                ('turno', models.CharField(blank=True, default='', max_length=100)),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('sucursal', models.CharField(blank=True, default='', max_length=100)),
                ('ips', models.BooleanField(default=False)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bono', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
