# Generated by Django 5.2 on 2026-04-02 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_turno_alter_funcionario_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('minutos_atraso', models.PositiveIntegerField(default=0)),
                ('llego_tarde', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.funcionario')),
            ],
            options={
                'ordering': ['-fecha', '-hora_entrada'],
                'unique_together': {('funcionario', 'fecha')},
            },
        ),
    ]
