# Generated by Django 5.2 on 2026-04-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('permiso_personal', 'Permiso personal'), ('reposo_medico', 'Reposo médico'), ('vacacion_provisional', 'Vacación provisional'), ('licencia_especial', 'Licencia especial'), ('otro', 'Otro')], default='permiso_personal', max_length=40)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('motivo', models.TextField(blank=True, default='')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='permisos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_licencias', to='core.funcionario')),
            ],
            options={
                'ordering': ['-fecha_desde', '-creado_en'],
            },
        ),
    ]
