# Generated by Django 5.2 on 2026-04-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historialaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
