# Generated by Django 5.2 on 2026-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_sucursal_funcionario_sucursal_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='hora_regreso_almuerzo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='hora_salida_almuerzo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
