# Generated by Django 5.2 on 2026-04-09 19:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_asistencia_hora_regreso_almuerzo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='porcentaje_limite_deuda',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje máximo recomendado de deuda sobre salario base.', max_digits=5),
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vale_compra', 'Vale compra'), ('prestamo', 'Préstamo'), ('adelanto', 'Adelanto'), ('otro', 'Otro')], default='vale_compra', max_length=30)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aplicar_en_nomina', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='core.funcionario')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
