# Generated by Django 5.2 on 2026-04-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_funcionario_porcentaje_limite_deuda_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='banco',
            field=models.CharField(blank=True, choices=[('', '---------'), ('itau', 'Itaú'), ('continental', 'Continental'), ('sudameris', 'Sudameris'), ('basa', 'Basa'), ('gnb', 'GNB'), ('familiar', 'Familiar'), ('ueno', 'Ueno'), ('vision', 'Visión'), ('atlas', 'Atlas'), ('rio', 'Banco Río'), ('otro', 'Otro')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='modalidad_cobro',
            field=models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('efectivo', 'Cobrar en efectivo')], default='transferencia', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero_cuenta',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('', '---------'), ('ahorro', 'Caja de ahorro'), ('corriente', 'Cuenta corriente')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='NominaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bono_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bono_icl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salario_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_ips', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_deudas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salario_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('modalidad_cobro', models.CharField(blank=True, default='', max_length=20)),
                ('banco', models.CharField(blank=True, default='', max_length=30)),
                ('tipo_cuenta', models.CharField(blank=True, default='', max_length=20)),
                ('numero_cuenta', models.CharField(blank=True, default='', max_length=50)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('extracto_firmado', models.FileField(blank=True, null=True, upload_to='nomina/extractos_firmados/')),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='nomina/comprobantes/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='core.funcionario')),
            ],
            options={
                'ordering': ['-anio', '-mes', 'funcionario__apellido', 'funcionario__nombre'],
                'unique_together': {('funcionario', 'mes', 'anio')},
            },
        ),
    ]
