# Generated by Django 5.2 on 2026-04-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_funcionario_banco_funcionario_modalidad_cobro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Cajera/o', 'Cajera/o'), ('Encargado/a', 'Encargado/a'), ('Marketing', 'Marketing'), ('Digitación', 'Digitación'), ('Cierre de Compras', 'Cierre de Compras'), ('Compras', 'Compras'), ('Tesorería', 'Tesorería'), ('Pagos', 'Pagos'), ('RRHH', 'RRHH'), ('Contabilidad', 'Contabilidad'), ('Financiero', 'Financiero'), ('Repositor/a', 'Repositor/a'), ('Recepcionista', 'Recepcionista'), ('Balconista', 'Balconista'), ('Carnicero', 'Carnicero'), ('Auxiliar', 'Auxiliar'), ('Auxiliar RRHH', 'Auxiliar RRHH'), ('Delivery', 'Delivery'), ('Pizzero', 'Pizzero'), ('Chapero', 'Chapero'), ('Ayudante', 'Ayudante'), ('Limpiadora', 'Limpiadora'), ('Mozo', 'Mozo'), ('Bartender', 'Bartender'), ('Churrasquero', 'Churrasquero'), ('Pasador', 'Pasador'), ('Panadero/a', 'Panadero/a'), ('Confitero/a', 'Confitero/a'), ('Saladero/a', 'Saladero/a'), ('Buffet', 'Buffet'), ('Cocinera', 'Cocinera'), ('Ayudante de Cocina', 'Ayudante de Cocina'), ('Depositero', 'Depositero'), ('Recepcionista de Mercaderías', 'Recepcionista de Mercaderías'), ('Gerente', 'Gerente'), ('Informático', 'Informático'), ('Técnico de Mantenimiento', 'Técnico de Mantenimiento')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=2899048, max_digits=12),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sector',
            field=models.CharField(blank=True, choices=[('Administración', 'Administración'), ('RRHH', 'RRHH'), ('Panadería', 'Panadería'), ('Financiero', 'Financiero'), ('Caja', 'Caja'), ('Salón', 'Salón'), ('Carnicería', 'Carnicería'), ('Hortifrut', 'Hortifrut'), ('Depósito', 'Depósito'), ('Recepción', 'Recepción'), ('Mantenimiento', 'Mantenimiento'), ('Limpieza', 'Limpieza'), ('Cocina', 'Cocina'), ('Copa', 'Copa'), ('Churrasquería', 'Churrasquería')], default='', max_length=100),
        ),
    ]
