# Generated by Django 5.2 on 2026-04-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base_default', models.DecimalField(decimal_places=2, default=2899048, max_digits=12)),
                ('porcentaje_limite_deuda_default', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('tolerancia_minutos_default', models.PositiveIntegerField(default=1)),
                ('observacion_general', models.TextField(blank=True, default='')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración general',
                'verbose_name_plural': 'Configuraciones generales',
            },
        ),
    ]
