# Generated by Django 5.2 on 2026-04-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_configuraciongeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='biometrico_fullscreen_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='biometrico_pausa_aviso_ms',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='biometrico_pausa_error_ms',
            field=models.PositiveIntegerField(default=2200),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='biometrico_pausa_exito_ms',
            field=models.PositiveIntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='biometrico_segundos_lectura',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='biometrico_sonidos_activos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='nombre_sistema',
            field=models.CharField(default='ClockIn', max_length=100),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='subtitulo_sistema',
            field=models.CharField(default='Sistema Web', max_length=150),
        ),
    ]
