# Generated by Django 5.2 on 2026-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_configuraciongeneral_biometrico_fullscreen_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='bancos_personalizados',
            field=models.TextField(blank=True, default='Itaú\nContinental\nSudameris\nBasa\nGNB\nFamiliar\nUeno\nVisión\nAtlas\nBanco Río\nOtro'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='cargos_personalizados',
            field=models.TextField(blank=True, default='Cajera/o\nEncargado/a\nMarketing\nDigitación\nCierre de Compras\nCompras\nTesorería\nPagos\nRRHH\nContabilidad\nFinanciero\nRepositor/a\nRecepcionista\nBalconista\nCarnicero\nAuxiliar\nAuxiliar RRHH\nDelivery\nPizzero\nChapero\nAyudante\nLimpiadora\nMozo\nBartender\nChurrasquero\nPasador\nPanadero/a\nConfitero/a\nSaladero/a\nBuffet\nCocinera\nAyudante de Cocina\nDepositero\nRecepcionista de Mercaderías\nGerente\nInformático\nTécnico de Mantenimiento'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='color_primario',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='sectores_personalizados',
            field=models.TextField(blank=True, default='Administración\nRRHH\nPanadería\nFinanciero\nCaja\nSalón\nCarnicería\nHortifrut\nDepósito\nRecepción\nMantenimiento\nLimpieza\nCocina\nCopa\nChurrasquería'),
        ),
    ]
