# Generated by Django 5.2 on 2026-04-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configuraciongeneral_bancos_personalizados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='color_primario',
            field=models.CharField(default='azul', max_length=20),
        ),
    ]
