# Generated by Django 5.2 on 2026-04-17 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_configuraciongeneral_color_primario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('fecha_calculo', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo_salida', models.CharField(choices=[('despido_justa_causa', 'Despido por Justa Causa'), ('despido_sin_justa_causa', 'Despido sin Justa Causa'), ('renuncia', 'Renuncia'), ('abandono', 'Abandono')], max_length=40)),
                ('motivo_observacion', models.TextField(blank=True, default='')),
                ('salario_base_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bono_base_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('antiguedad_anios', models.PositiveIntegerField(default=0)),
                ('antiguedad_meses', models.PositiveIntegerField(default=0)),
                ('antiguedad_dias', models.PositiveIntegerField(default=0)),
                ('dias_trabajados_pendientes', models.PositiveIntegerField(default=0)),
                ('salario_pendiente_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vacaciones_causadas_pendientes_dias', models.PositiveIntegerField(default=0)),
                ('vacaciones_causadas_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vacaciones_proporcionales_dias', models.PositiveIntegerField(default=0)),
                ('vacaciones_proporcionales_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aguinaldo_proporcional_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preaviso_dias_corresponde', models.PositiveIntegerField(default=0)),
                ('preaviso_dias_otorgados', models.PositiveIntegerField(default=0)),
                ('preaviso_cumplido', models.BooleanField(default=False)),
                ('descontar_preaviso', models.BooleanField(default=False)),
                ('preaviso_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnizacion_dias', models.PositiveIntegerField(default=0)),
                ('indemnizacion_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ips_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deudas_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_haberes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_liquidacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requiere_revision_juridica', models.BooleanField(default=False)),
                ('alerta_revision', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='core.funcionario')),
            ],
            options={
                'ordering': ['-fecha_calculo', '-creado_en'],
            },
        ),
    ]
