# Generated by Django 5.2 on 2026-04-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dialibre'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.empresa'),
        ),
    ]
