# Generated by Django 5.2 on 2026-04-25 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_turno_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha_hora_real_sistema',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='marcado_manual_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcaciones_manuales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='motivo_marcacion_manual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='origen_marcacion',
            field=models.CharField(choices=[('lector', 'Lector facial'), ('manual', 'Manual')], default='lector', max_length=20),
        ),
    ]
