# Generated by Django 5.2 on 2026-04-26 01:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_asistencia_fecha_hora_real_sistema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('cerrado', models.BooleanField(default=True)),
                ('cerrado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, default='')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio', 'empresa')},
            },
        ),
    ]
