# Generated by Django 5.2 on 2026-05-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_empresa_direccion_empresa_email_empresa_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='cargos_personalizados',
            field=models.TextField(blank=True, default='Cajera/o\nEncargado/a\nMarketing\nDigitación\nCierre de Compras\nCompras\nTesorería\nPagos\nRRHH\nContabilidad\nFinanciero\nRepositor/a\nRecepcionista\nBalconista\nCarnicero\nAuxiliar\nAuxiliar RRHH\nDelivery\nPizzero\nChapero\nAyudante\nLimpiadora\nMozo\nBartender\nChurrasquero\nPasador\nPanadero/a\nConfitero/a\nSaladero/a\nBuffet\nCocinera\nAyudante de Cocina\nDepositero\nRecepcionista de Mercaderías\nGerente\nInformático\nTécnico de Mantenimiento\nInventario\nLogistica'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='sectores_personalizados',
            field=models.TextField(blank=True, default='Administración\nRRHH\nPanadería\nFinanciero\nCaja\nSalón\nCarnicería\nHortifrut\nDepósito\nRecepción\nMantenimiento\nLimpieza\nCocina\nCopa\nFríos\nChurrasquería'),
        ),
    ]
