# Generated by Django 5.2 on 2026-05-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_configuraciongeneral_cargos_personalizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='ausencias_descuento',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='descuento_ausencias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
