# Generated by Django 5.2 on 2026-05-19 00:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_planillasemanalfuncionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amonestacion', 'Sanción Disciplinaria / Amonestación'), ('preaviso', 'Preaviso'), ('abandono', 'Abandono de Trabajo'), ('permiso', 'Comunicación de Permiso'), ('ausencia', 'Ausencia Injustificada'), ('suspension', 'Suspensión Disciplinaria'), ('citacion_descargo', 'Citación a Descargo'), ('cambio_cargo_sector', 'Cambio de Cargo / Sector / Sucursal'), ('memorandum', 'Memorándum Interno')], max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_referencia', models.DateField(blank=True, null=True)),
                ('asunto', models.CharField(blank=True, default='', max_length=255)),
                ('detalle_hecho', models.TextField(blank=True, default='')),
                ('contenido', models.TextField(blank=True, default='')),
                ('observacion_interna', models.TextField(blank=True, default='')),
                ('requiere_firma', models.BooleanField(default=True)),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('entregada', 'Entregada'), ('firmada', 'Firmada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('adjunto_firmado', models.FileField(blank=True, null=True, upload_to='comunicaciones/firmadas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones', to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='core.funcionario')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones_generadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones', to='core.sucursal')),
            ],
            options={
                'ordering': ['-fecha_emision', '-creado_en'],
            },
        ),
    ]
