# Generated by Django 5.2 on 2026-05-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_comunicacionlaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='fecha_notificacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
