# Generated by Django 5.2 on 2026-05-19 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_vacacion_fecha_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AguinaldoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('total_remuneraciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_aguinaldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('meses_computados', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aguinaldos', to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aguinaldos', to='core.funcionario')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aguinaldos', to='core.sucursal')),
            ],
            options={
                'ordering': ['-anio', 'funcionario__apellido', 'funcionario__nombre'],
                'unique_together': {('funcionario', 'anio')},
            },
        ),
    ]
