# Generated by Django 5.2 on 2026-05-19 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_aguinaldoanual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanillaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('banco', models.CharField(max_length=120)),
                ('formato', models.CharField(choices=[('csv', 'CSV'), ('txt', 'TXT')], default='csv', max_length=10)),
                ('total_funcionarios', models.PositiveIntegerField(default=0)),
                ('total_importe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada'), ('exportada', 'Exportada')], default='borrador', max_length=20)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_bancarias', to='core.empresa')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_bancarias_generadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_bancarias', to='core.sucursal')),
            ],
            options={
                'ordering': ['-anio', '-mes', '-generado_en'],
            },
        ),
    ]
