# Generated by Django 5.2 on 2026-05-19 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_planillabancaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoHorasMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('generado', 'Horas generadas'), ('descuento', 'Descuento por faltante'), ('horas_tomadas', 'Horas tomadas'), ('ajuste_manual', 'Ajuste manual')], max_length=30)),
                ('minutos', models.IntegerField(default=0)),
                ('saldo_anterior', models.IntegerField(default=0)),
                ('saldo_nuevo', models.IntegerField(default=0)),
                ('origen', models.CharField(blank=True, default='sistema', max_length=50)),
                ('observacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_banco_horas_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_banco_horas', to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_horas', to='core.funcionario')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_banco_horas', to='core.sucursal')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
