# Generated by Django 5.2 on 2026-05-22 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_bancohorasmovimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['empresa__nombre', 'nombre']},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='nominamensual',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='permisolicencia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('empresa', 'nombre')},
        ),
    ]
