# Generated by Django 5.2 on 2026-05-22 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_turno_options_asistencia_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='core.empresa'),
        ),
    ]
