# Generated by Django 5.2 on 2026-05-23 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_deuda_empresa_vacacion_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cargo_gerente',
            field=models.CharField(blank=True, default='Gerente General', max_length=150),
        ),
        migrations.AddField(
            model_name='empresa',
            name='firma_gerente',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/firmas/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_gerente',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='DocumentoFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('tipo_documento', models.CharField(max_length=80)),
                ('documento_id', models.PositiveIntegerField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, default='', max_length=180)),
                ('hash_documento', models.CharField(blank=True, default='', max_length=128)),
                ('firmado_por_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('firmado_por_cargo', models.CharField(blank=True, default='', max_length=150)),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
                ('valido', models.BooleanField(default=True)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_emitidos', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_firmados', to='core.empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_firmados', to='core.funcionario')),
            ],
            options={
                'ordering': ['-emitido_en'],
            },
        ),
    ]
