# Generated by Django 5.2 on 2026-06-03 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_empresa_cargo_gerente_empresa_firma_gerente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='alergias',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='contacto_emergencia_parentesco',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='enfermedad_importante',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='medicacion_actual',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nacionalidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='seguro_medico',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_sangre',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ConductaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('reconocimiento', 'Reconocimiento'), ('felicitacion', 'Felicitación'), ('observacion', 'Observación'), ('amonestacion', 'Amonestación'), ('apercibimiento', 'Apercibimiento'), ('suspension', 'Suspensión'), ('otro', 'Otro')], default='observacion', max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='funcionarios/conducta/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductas', to='core.funcionario')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cedula_frente', 'Cédula frente'), ('cedula_dorso', 'Cédula dorso'), ('contrato', 'Contrato laboral'), ('curriculum', 'Currículum'), ('certificado', 'Certificado'), ('antecedente', 'Antecedente'), ('medico', 'Documento médico'), ('otro', 'Otro')], default='otro', max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('archivo', models.FileField(upload_to='funcionarios/documentos/')),
                ('observacion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_personales', to='core.funcionario')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialLaboralFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('ascenso', 'Ascenso'), ('traslado', 'Traslado'), ('cambio_cargo', 'Cambio de cargo'), ('cambio_sucursal', 'Cambio de sucursal'), ('reincorporacion', 'Reincorporación'), ('otro', 'Otro')], default='otro', max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='funcionarios/historial_laboral/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_laboral', to='core.funcionario')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSalarialFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('salario_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salario_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bono_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bono_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo', models.CharField(blank=True, default='', max_length=180)),
                ('observacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_salarial', to='core.funcionario')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
