# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_funcionario_alergias_funcionario_ciudad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquidacion",
            name="tipo_salida",
            field=models.CharField(
                choices=[
                    ("despido_justa_causa", "Despido por Justa Causa"),
                    ("periodo_prueba", "Periodo de Prueba"),
                    ("despido_sin_justa_causa", "Despido sin Justa Causa"),
                    ("renuncia", "Renuncia"),
                    ("abandono", "Abandono"),
                ],
                max_length=40,
            ),
        ),
    ]
