# Generated by Codex on 2026-06-18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0035_alter_liquidacion_tipo_salida"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuscripcionSistema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre_cliente", models.CharField(blank=True, default="ClockIn", max_length=150)),
                ("estado", models.CharField(choices=[("activa", "Activa"), ("pausada", "Pausada")], default="activa", max_length=20)),
                ("fecha_inicio", models.DateField(default=django.utils.timezone.localdate)),
                ("fecha_proximo_pago", models.DateField(default=django.utils.timezone.localdate)),
                ("fecha_ultimo_pago", models.DateField(blank=True, null=True)),
                ("dias_gracia", models.PositiveIntegerField(default=0)),
                ("bloquear_al_vencer", models.BooleanField(default=True)),
                ("contacto_pago", models.CharField(blank=True, default="", max_length=180)),
                ("mensaje_bloqueo", models.TextField(blank=True, default="El servicio se encuentra pendiente de regularizacion. Contacte al administrador para reactivar el acceso.")),
                ("observacion_interna", models.TextField(blank=True, default="")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suscripciones_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripcion del sistema",
                "verbose_name_plural": "Suscripciones del sistema",
            },
        ),
    ]
