# Generated by Codex on 2026-06-18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0036_suscripcionsistema"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoSuscripcionSistema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_pago", models.DateField(default=django.utils.timezone.localdate)),
                ("meses_cubiertos", models.PositiveSmallIntegerField(choices=[(1, "Mensual"), (3, "Trimestral"), (6, "Semestral"), (12, "Anual")], default=1)),
                ("monto", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("comprobante", models.CharField(blank=True, default="", max_length=120)),
                ("observacion", models.TextField(blank=True, default="")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_suscripcion_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="core.suscripcionsistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de suscripcion",
                "verbose_name_plural": "Pagos de suscripcion",
                "ordering": ["-fecha_pago", "-creado_en"],
            },
        ),
    ]
