# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_pagosuscripcionsistema"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="nombre_comercial",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="empresa",
            name="razon_social",
            field=models.CharField(blank=True, default="", max_length=180),
        ),
        migrations.AddField(
            model_name="empresa",
            name="color_primario",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="empresa",
            name="color_secundario",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tema_visual",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="empresa",
            name="estado",
            field=models.CharField(choices=[("activa", "Activa"), ("suspendida", "Suspendida")], default="activa", max_length=20),
        ),
        migrations.AddField(
            model_name="empresa",
            name="plan_contratado",
            field=models.CharField(choices=[("basico", "Basico"), ("profesional", "Profesional"), ("empresarial", "Empresarial")], default="profesional", max_length=30),
        ),
        migrations.AddField(
            model_name="empresa",
            name="fecha_vencimiento_suscripcion",
            field=models.DateField(blank=True, null=True),
        ),
    ]
