# Generated by Django 5.2 on 2026-06-18 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_empresa_saas_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialaccion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_historial', to='core.empresa'),
        ),
    ]
