# Generated by Django 5.2 on 2026-07-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_empresa_icl_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='salario_diferenciado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usa_salario_diferenciado',
            field=models.BooleanField(default=False),
        ),
    ]
