# Generated by Django 5.2 on 2026-07-16 00:46

from django.db import migrations, models


def completar_snapshots_liquidaciones(apps, schema_editor):
    Liquidacion = apps.get_model("core", "Liquidacion")
    for liquidacion in Liquidacion.objects.all().iterator():
        liquidacion.modalidad_salarial_snapshot = liquidacion.modalidad_salarial_snapshot or "normal"
        liquidacion.salario_bruto_aplicable_snapshot = (
            (liquidacion.salario_base_snapshot or 0) + (liquidacion.bono_base_snapshot or 0)
        )
        liquidacion.descuento_ips_calculado_snapshot = liquidacion.ips_monto or 0
        liquidacion.total_haberes_automatico = liquidacion.total_haberes or 0
        liquidacion.total_descuentos_automatico = liquidacion.total_descuentos or 0
        liquidacion.total_liquidacion_automatico = liquidacion.total_liquidacion or 0
        liquidacion.save(update_fields=[
            "modalidad_salarial_snapshot",
            "salario_bruto_aplicable_snapshot",
            "descuento_ips_calculado_snapshot",
            "total_haberes_automatico",
            "total_descuentos_automatico",
            "total_liquidacion_automatico",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_funcionario_salario_diferenciado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='descuento_ips_calculado_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='modalidad_salarial_snapshot',
            field=models.CharField(blank=True, default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='porcentaje_ips_snapshot',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='salario_bruto_aplicable_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='salario_diferenciado_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='total_descuentos_automatico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='total_haberes_automatico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='total_liquidacion_automatico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(completar_snapshots_liquidaciones, migrations.RunPython.noop),
    ]
