# Generated by Django 5.2 on 2026-07-16 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_liquidacion_descuento_ips_calculado_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='permite_ajuste_manual_liquidacion',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AjusteManualLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('haber', 'Haber'), ('descuento', 'Descuento')], max_length=20)),
                ('concepto', models.CharField(max_length=150)),
                ('importe_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('importe_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('anulado', 'Anulado')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, default='')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_liquidacion_anulados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_liquidacion_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_liquidacion', to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_liquidacion', to='core.funcionario')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_manuales', to='core.liquidacion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
