# Generated by Django 5.2 on 2026-07-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_empresa_permite_ajuste_manual_liquidacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='origen_marcacion',
            field=models.CharField(choices=[('lector', 'Lector facial'), ('biometrico_tablet', 'Biométrico tablet'), ('biometrico_celular', 'Biométrico celular'), ('manual', 'Manual')], default='lector', max_length=20),
        ),
    ]
