# Generated by Django 5.2 on 2026-08-26 23:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_asistencia_origen_marcacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diarista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('cedula', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cantidad_dias_contratados', models.PositiveIntegerField(default=1)),
                ('monto_diario_acordado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_calculo', models.CharField(choices=[('por_dia_trabajado', 'Por día efectivamente trabajado'), ('por_dias_contratados', 'Por días contratados')], default='por_dia_trabajado', max_length=30)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('funcion_temporal', models.CharField(blank=True, default='', max_length=150)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaristas_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaristas', to='core.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaristas', to='core.sucursal')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaristas', to='core.turno')),
            ],
            options={
                'verbose_name': 'Diarista',
                'verbose_name_plural': 'Diaristas',
                'ordering': ['-fecha_inicio', 'apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='PagoDiarista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('periodo_desde', models.DateField()),
                ('periodo_hasta', models.DateField()),
                ('dias_calculados', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monto_diario_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adicionales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion', models.TextField(blank=True, default='')),
                ('concepto_adicional', models.CharField(blank=True, default='', max_length=180)),
                ('motivo_ajuste', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generado', 'Generado'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('numero_comprobante', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('motivo_anulacion', models.TextField(blank=True, default='')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_diaristas_anulados', to=settings.AUTH_USER_MODEL)),
                ('diarista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.diarista')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_diaristas', to='core.empresa')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_diaristas_generados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_diaristas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Pago de diarista',
                'verbose_name_plural': 'Pagos de diaristas',
                'ordering': ['-fecha_pago', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaDiarista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('minutos_trabajados', models.PositiveIntegerField(default=0)),
                ('minutos_atraso', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('trabajado', 'Trabajado'), ('ausente', 'Ausente'), ('incompleto', 'Incompleto')], default='programado', max_length=20)),
                ('pago_estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('incluido', 'Incluido en pago'), ('pagado', 'Pagado'), ('reabierto', 'Reabierto')], default='pendiente', max_length=20)),
                ('origen_marcacion', models.CharField(choices=[('manual', 'Manual'), ('biometrico_tablet', 'Biométrico tablet'), ('biometrico_celular', 'Biométrico celular')], default='manual', max_length=20)),
                ('observacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_diaristas', to='core.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_diaristas', to='core.sucursal')),
                ('diarista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.diarista')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas', to='core.pagodiarista')),
            ],
            options={
                'verbose_name': 'Asistencia de diarista',
                'verbose_name_plural': 'Asistencias de diaristas',
                'ordering': ['-fecha', 'diarista__apellidos', 'diarista__nombres'],
            },
        ),
        migrations.AddIndex(
            model_name='diarista',
            index=models.Index(fields=['empresa', 'estado', 'fecha_inicio'], name='core_diaris_empresa_0669c1_idx'),
        ),
        migrations.AddIndex(
            model_name='diarista',
            index=models.Index(fields=['empresa', 'cedula'], name='core_diaris_empresa_52557d_idx'),
        ),
        migrations.AddIndex(
            model_name='diarista',
            index=models.Index(fields=['sucursal', 'estado'], name='core_diaris_sucursa_81f54e_idx'),
        ),
        migrations.AddIndex(
            model_name='pagodiarista',
            index=models.Index(fields=['empresa', 'estado', 'fecha_pago'], name='core_pagodi_empresa_74644c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagodiarista',
            index=models.Index(fields=['diarista', 'estado'], name='core_pagodi_diarist_06ab69_idx'),
        ),
        migrations.AddIndex(
            model_name='pagodiarista',
            index=models.Index(fields=['numero_comprobante'], name='core_pagodi_numero__16d52e_idx'),
        ),
        migrations.AddIndex(
            model_name='asistenciadiarista',
            index=models.Index(fields=['empresa', 'fecha', 'estado'], name='core_asiste_empresa_25b9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='asistenciadiarista',
            index=models.Index(fields=['diarista', 'fecha'], name='core_asiste_diarist_0c3919_idx'),
        ),
        migrations.AddIndex(
            model_name='asistenciadiarista',
            index=models.Index(fields=['pago_estado'], name='core_asiste_pago_es_023277_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistenciadiarista',
            constraint=models.UniqueConstraint(fields=('diarista', 'fecha'), name='uniq_asistencia_diarista_fecha'),
        ),
    ]
