# Generated by Django 5.2 on 2026-08-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_diarista_pagodiarista_asistenciadiarista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodiarista',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
