# Generated by Django 5.2 on 2026-08-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_pagodiarista_numero_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo_documento',
            field=models.CharField(choices=[('CI', 'Cédula de Identidad'), ('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CI', max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cedula',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='funcionario',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'cedula'), name='uniq_funcionario_tipo_documento_cedula'),
        ),
    ]
