# Generated by Django 5.2 on 2026-04-18 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('dashboard', 'Dashboard'), ('empresas', 'Empresas'), ('sucursales', 'Sucursales'), ('funcionarios', 'Funcionarios'), ('turnos', 'Turnos'), ('asistencia', 'Asistencia'), ('dias_libres', 'Días Libres'), ('deudas', 'Deudas'), ('nomina', 'Nómina'), ('biometrico', 'Biométrico'), ('permisos', 'Permisos / Licencias'), ('vacaciones', 'Vacaciones'), ('icl', 'ICL'), ('reportes', 'Reportes'), ('historial', 'Historial'), ('liquidacion', 'Liquidación'), ('configuracion', 'Configuración')], max_length=50)),
                ('puede_ver', models.BooleanField(default=False)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('puede_aprobar', models.BooleanField(default=False)),
                ('puede_confirmar', models.BooleanField(default=False)),
                ('puede_pagar', models.BooleanField(default=False)),
                ('puede_anular', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_personalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de usuario',
                'verbose_name_plural': 'Permisos de usuarios',
                'ordering': ['usuario', 'modulo'],
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
