# Generated by Django 5.2 on 2026-05-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisousuario',
            name='modulo',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('empresas', 'Empresas'), ('sucursales', 'Sucursales'), ('funcionarios', 'Funcionarios'), ('usuarios', 'Usuarios y Permisos'), ('turnos', 'Turnos'), ('dias_libres', 'Días Libres'), ('asistencia', 'Asistencia'), ('biometrico', 'Biométrico'), ('banco_horas', 'Banco de Horas'), ('permisos', 'Permisos / Licencias'), ('vacaciones', 'Vacaciones'), ('comunicaciones', 'Comunicaciones'), ('deudas', 'Deudas'), ('nomina', 'Nómina'), ('aguinaldo', 'Aguinaldo'), ('planilla_bancaria', 'Planilla Bancaria'), ('liquidacion', 'Liquidación'), ('icl', 'ICL'), ('reportes', 'Reportes'), ('historial', 'Historial'), ('configuracion', 'Configuración')], max_length=50),
        ),
    ]
