# Generated by Django 5.2 on 2026-07-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_funcionario_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisousuario',
            name='puede_ajustar',
            field=models.BooleanField(default=False),
        ),
    ]
