# Generated by Django 5.2 on 2026-07-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_permisousuario_puede_ajustar'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisousuario',
            name='puede_exportar',
            field=models.BooleanField(default=False),
        ),
    ]
