# Generated by Django 5.2 on 2026-07-10 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_empresa_icl_activo'),
        ('portal_funcionario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSolicitudDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('certificado_laboral', 'Certificado laboral'), ('constancia_antiguedad', 'Constancia de antigüedad'), ('constancia_horario', 'Constancia de horario'), ('constancia_banco', 'Constancia para banco'), ('copia_contrato', 'Copia de contrato'), ('otro', 'Otro')], max_length=40)),
                ('motivo', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('observacion_operador', models.TextField(blank=True, default='')),
                ('archivo_final', models.FileField(blank=True, null=True, upload_to='portal/documentos_finales/')),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_portal', to='core.documentofuncionario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_solicitudes_documentos', to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_solicitudes_documentos', to='core.funcionario')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_documentos_revisados', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_documentos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PortalSolicitudMarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida_almuerzo', 'Salida a almuerzo'), ('regreso_almuerzo', 'Regreso de almuerzo'), ('salida', 'Salida'), ('otro', 'Otro')], max_length=30)),
                ('hora_solicitada', models.TimeField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='portal/marcaciones/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observacion_operador', models.TextField(blank=True, default='')),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_correccion_portal', to='core.asistencia')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_solicitudes_marcacion', to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_solicitudes_marcacion', to='core.funcionario')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_marcaciones_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_marcaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
