# Generated by Django 5.2 on 2026-07-10 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_empresa_icl_activo'),
        ('portal_funcionario', '0002_portalsolicituddocumento_portalsolicitudmarcacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalDescargoComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='portal/descargos/')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('revisado', 'Revisado'), ('anulado', 'Anulado')], default='enviado', max_length=20)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comunicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_descargos', to='core.comunicacionlaboral')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_descargos', to='core.empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_descargos_enviados', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_descargos', to='core.funcionario')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_descargos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PortalSugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('general', 'General'), ('clima', 'Clima laboral'), ('seguridad', 'Seguridad'), ('procesos', 'Procesos'), ('beneficios', 'Beneficios'), ('otro', 'Otro')], default='general', max_length=30)),
                ('asunto', models.CharField(max_length=180)),
                ('mensaje', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='portal/sugerencias/')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_revision', 'En revisión'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada'), ('anulada', 'Anulada')], default='recibida', max_length=20)),
                ('respuesta_operador', models.TextField(blank=True, default='')),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sugerencias', to='core.empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sugerencias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sugerencias', to='core.funcionario')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sugerencias_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
